# Generated by Django 2.2 on 2019-05-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
