# Generated by Django 2.2 on 2019-05-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomateSurvery',
            new_name='RoomateSurvey',
        ),
    ]
