# Generated by Django 2.2 on 2019-05-05 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190505_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_you_drink', models.BooleanField()),
                ('do_you_smoke', models.BooleanField()),
                ('are_you_sporty', models.BooleanField()),
                ('do_you_game', models.BooleanField()),
                ('type_of_gamer', models.CharField(choices=[('iphone', 'iPhone Games'), ('fps', 'First person shooter'), ('smash', 'Super Smash'), ('na', 'None')], default='iphone', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomateSurvey',
        ),
    ]
